# encoding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

# General
wp_box: ubuntu/trusty64
chef_cookbook_path: ./provision

# Virtual machine
memory: 512
cpus: 1

linked_clone: false

# DB will be reset when provision
reset_db_on_provision: false

# User and Group
user: vagrant
group: vagrant

# SSL support
use_ssl: false

# Network
dev_url: kit.dev
dev_ip: 192.168.33.10
host_document_root: 'www'

# WordPress
version: latest
lang: en_US
title: Welcome to the Dev Kit
multisite: false
rewrite_structure: /archives/%post_id%

# Wordpress path
document_root: '/var/www'
siteurl: ''  # Path to the WP_SITEURL like "wp"
home: ''     # Path to the WP_HOME like "wp"

# Wordpress users
admin_user: admin
admin_pass: admin
admin_email: devkit@example.com

# WordPress Database
db_prefix: wp_
db_host: localhost

# Default Plugins
# Plugin's slug or url to the plugin's slug.
plugins:
- advanced-custom-fields
- timber-library
- sucuri-scanner
- force-regenerate-thumbnails
- query-monitor

# WordPress Default Theme
# Theme's slug or url to the theme's .zip.
theme: ''

# WordPress Options
options:
  blogdescription: Hello Dev Kit.

# The values of wp-config.php
force_ssl_admin: false
wp_debug: true
savequeries: false

# Theme unit testing
theme_unit_test: false
theme_unit_test_uri: https://wpcom-themes.svn.automattic.com/demo/theme-unit-test-data.xml
# theme_unit_test_uri: https://raw.githubusercontent.com/jawordpressorg/theme-test-data-ja/master/wordpress-theme-test-date-ja.xml
