slug: yww-project # lowercase, no spaces, URL-friendly
hostname: yww-project.dev
title: YWW project
multisite: false
rewrite_structure: /%postname%
admin_user: yeswework
admin_pass: shovelling
admin_email: info@yeswework.com
plugins:
  - advanced-custom-fields
  - timber-library
  - sucuri-scanner
  - force-regenerate-thumbnails
  - query-monitor
# - http://yeswework.com/_dev/plugins/register-structure.zip
# - http://yeswework.com/_dev/plugins/yww-admin-tweaks.zip
options:
  blogdescription: